---
name: policies_always_override_project_ci
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/489715
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175088
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/509986
milestone: '17.8'
group: group::security policies
type: beta
default_enabled: true
