---
name: resolve_vulnerability_in_mr
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/481532
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/164897
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/482753
milestone: '17.4'
group: group::security insights
type: beta
default_enabled: true
