---
name: security_policies_skip_ci
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/507835
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/507835
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/510849
milestone: '17.8'
group: group::security policies
type: beta
default_enabled: true
