---
name: vulnerability_filtering_by_identifier_group
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/508713
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175902
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/516877
milestone: '17.8'
group: group::security insights
type: beta
default_enabled: false
