---
name: vulnerability_report_owasp_2021
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142405
rollout_issue_url:
milestone: '16.9'
group: group::security insights
type: beta
default_enabled: false
