---
name: vulnerability_report_vr_badge
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/481530
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165525
rollout_issue_url:
milestone: '17.4'
group: group::threat insights
type: beta
default_enabled: true
