---
name: vulnerability_report_vr_filter
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/490323
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166312
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/486534
milestone: '17.5'
group: group::threat insights
type: beta
default_enabled: true
