---
name: zoekt_cache_search_responses
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137337
rollout_issue_url:
milestone: '16.7'
type: ops
group: group::global search
default_enabled: true
