---
name: zoekt_index_circuit_breaker
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/494260
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/168566
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/498316
milestone: '17.5'
group: group::global search
type: ops
default_enabled: false
