---
name: zoekt_internal_api_register_nodes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135853
rollout_issue_url:
milestone: '16.6'
type: ops
group: group::global search
default_enabled: true
