---
name: zoekt_node_assignment
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470044
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158044
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470149
milestone: '17.2'
group: group::global search
type: ops
default_enabled: true
