---
name: zoekt_node_backoffs
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136346
rollout_issue_url:
milestone: '16.6'
type: ops
group: group::global search
default_enabled: false
