---
name: zoekt_search_proxy
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/171867
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/502945
milestone: '17.9'
group: group::global search
type: ops
default_enabled: false
