---
name: zoekt_reallocation_task
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/148518
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/454487
milestone: '16.11'
group: group::global search
type: ops
default_enabled: true
