---
name: zoekt_increased_concurrency_indexing_task_worker
feature_issue_url:
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/503346
milestone: '17.6'
group: group::global search
type: ops
default_enabled: true
