---
name: authentication_logs_migration_for_allowlist
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/498125
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178429
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/514159
milestone: '17.9'
group: group::pipeline security
type: gitlab_com_derisk
default_enabled: false
