---
name: maven_extract_package_model
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/435824
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/171555
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/502402
milestone: '17.9'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
