---
name: advanced_search_work_item_uses_note_fields
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/15645
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/173719
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/503220
milestone: '17.7'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
