---
name: display_password_requirements
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/461828
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158789
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/509916
milestone: '17.3'
group: group::activation
type: gitlab_com_derisk
default_enabled: false
