---
name: epic_issues_through_work_item_service
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/504273
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179819
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/516175
milestone: '17.9'
group: group::product planning
type: gitlab_com_derisk
default_enabled: false
