---
name: fetch_arkose_data_exchange_payload
feature_issue_url: https://gitlab.com/gitlab-org/modelops/anti-abuse/team-tasks/-/issues/846
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/168939
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/500392
milestone: '17.6'
group: group::anti-abuse
type: gitlab_com_derisk
default_enabled: false
