---
name: group_vulnerability_scanners_using_statistics
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/513032
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178024
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/513300
milestone: '17.9'
group: group::security infrastructure
type: gitlab_com_derisk
default_enabled: false
