---
name: search_work_items_index_notes
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/508906
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/176144
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/510136
milestone: '17.8'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
