---
name: search_identifier_name_in_group_using_vulnerability_statistics
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/510091
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178886
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/515039
milestone: '17.9'
group: group::security infrastructure
type: gitlab_com_derisk
default_enabled: false
