---
name: search_mr_filter_target_branch
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/463375
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/160210
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/473699
milestone: '17.3'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
