---
name: spp_scan_diffs
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/469161
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/162782
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/480092
milestone: '17.5'
group: group::secret detection
type: gitlab_com_derisk
default_enabled: false
