---
name: zoekt_create_multiple_indices
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/473207
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/161154
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/500323
milestone: '17.6'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
