---
name: zoekt_optimized_performance_indexing
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/508910
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175413
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/508911
milestone: '17.8'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
