---
name: zoekt_reemit_events
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/511075
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177456
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/513084
milestone: '17.9'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
