---
name: zoekt_multimatch_frontend
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/450735
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/160955
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/472825
milestone: '17.3'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
