---
name: new_issue_attachment_from_vulnerability_bulk_action
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373814
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178686
rollout_issue_url:
milestone: '17.9'
group: group::security insights
type: wip
default_enabled: false
