---
name: sbom_ingest_unknown_licenses_with_count
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/482764
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179373
rollout_issue_url:
milestone: '17.9'
group: group::security insights
type: wip
default_enabled: false
