---
name: todos_bulk_actions
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/16564
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179403
rollout_issue_url:
milestone: '17.9'
group: group::personal productivity
type: wip
default_enabled: false
