---
name: work_item_description_templates
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/512208
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177856
rollout_issue_url:
milestone: '17.9'
group: group::product planning
type: wip
default_enabled: false
