---
name: ai_duo_chat_sub_features_settings
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/473005
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/163600
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/480893
milestone: '17.4'
group: group::custom models
type: wip
default_enabled: false
