---
name: auto_assign_duo_seat
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/500104
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/174400
rollout_issue_url:
milestone: '17.7'
group: group::activation
type: wip
default_enabled: false
