---
name: custom_ability_read_admin_monitoring
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/507960
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179439
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/515665
milestone: '17.9'
group: group::authorization
type: wip
default_enabled: false
