---
name: custom_ability_read_admin_cicd
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/507960
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177233
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/512831
milestone: '17.9'
group: group::authorization
type: wip
default_enabled: false
