---
name: enhanced_vulnerability_bulk_actions
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/13216
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/178696
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/515204
milestone: '17.9'
group: group::security insights
type: wip
default_enabled: false
