---
name: exclude_license_packages
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/499147
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/499142
milestone: '17.7'
group: group::security policies
type: wip
default_enabled: false
