---
name: group_level_dependencies_filtering_by_packager
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/12654
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/154390
rollout_issue_url:
milestone: '17.2'
group: group::security insights
type: wip
default_enabled: false
