---
name: scan_execution_policy_action_limit_group
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/436545
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146760
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/468918
milestone: '17.4'
group: group::security policies
type: wip
default_enabled: false
