---
name: vulnerability_severity_override
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/512889
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177685
rollout_issue_url:
milestone: '17.9'
group: group::security platform management
type: wip
default_enabled: false
