---
description: Call made to the Vulnerability API.
internal_events: true
action: called_vulnerability_api
identifiers:
- project
- namespace
- user
product_group: security_infrastructure
product_categories:
- vulnerability_management
milestone: '17.8'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175762
tiers:
- ultimate
