---
title: Manage vulnerabilities
name: admin_vulnerability
description: Edit the vulnerability object, including the status and linking an issue. Includes the `read_vulnerability` permission actions.
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/412536
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121534
feature_category: vulnerability_management
milestone: '16.1'
group_ability: true
enabled_for_group_access_levels: [40, 50]
project_ability: true
enabled_for_project_access_levels: [40, 50]
requirements:
  - read_vulnerability
available_from_access_level: 40
