---
api_type: boolean
attr: secret_push_protection_available
clusterwide: true
column: secret_push_protection_available
db_type: boolean
default: 'false'
description: Allow projects to enable secret push protection. This does not enable
  secret push protection. When you enable this feature, you accept the [GitLab Testing
  Agreement](https://handbook.gitlab.com/handbook/legal/testing-agreement/). Ultimate
  only.
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
